/*
* BANCO CRIADO COM CARINHO POR IGHOR DRUMMOND.
* DATA: 07/09/2024
* OBJETIVO: CRIAR BANCO E SUA TABELA 
*/  

# CRIANDO BANCO DE DADOS
CREATE DATABASE DB_FOCUSMANAGE CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

# USANDO O BANCO
USE DB_FOCUSMANAGE;

# CRIANDO TABELAS 
/*
TABELA: TASK
DESCRIÇÃO: RESPONSÁVEL POR ARMAZENAR AS TAREFAS
DATA: 07/09/2024
PROGRAMADOR(A): IGHOR DRUMMOND
*/
CREATE TABLE TASK(
    id_task INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name_task VARCHAR(100) NOT NULL DEFAULT '',
    description_task TEXT NOT NULL,
    status_task BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);