<!DOCTYPE html>
<html>
    <head>
        <!-- Meta tags Obrigatórias -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">  
        <meta name="description" content="Crie suas tarefas de uma forma simpático e incrível">
        <meta name="keywords" content="tarefas, lista, agenda, lista de tarefa, criar tarefas">
        <meta name="author" content="FocusManage">

        <!-- Meta tags para SEO -->
        <meta name="robots" content="index, follow">
        <meta name="googlebot" content="index, follow"> 

        <!-- Meta tags para redes sociais -->
        <meta property="og:title" content="FocusManage - Criador de Tarefas">
        <meta property="og:description" content="Crie sua tarefa de uma forma incrível e estilosa!">
        <meta property="og:type" content="website">

        <!-- Bootstrap 5 -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

        <!-- Normalize -->
        <link rel="stylesheet" type="text/css" href="assets/css/normalize.css">

        <!-- Favicon -->
        <link rel="icon" href="assets/image/icone.png">

        <!-- HTML5Shiv -->
        <!--[if lt IE 9]>
            <script src="http://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <![endif]-->    

        <!-- Tema Bootstrap do Flatpickr -->
        <link href="https://cdn.jsdelivr.net/npm/flatpickr/dist/themes/material_blue.css" rel="stylesheet">

        <!-- Estilo Padrão -->
        <link rel="stylesheet" type="text/css" href="assets/css/style.css">

        <!-- Titulo do Site -->
        <title>FocusManage</title>
    </head>
    <body>
        <!-- Cabeçalho -->
        <nav class="navbar navbar-expand-lg navbar-blue bg-primary sticky-top">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse px-4">
                <a class="navbar-brand text-white">
                    FocusManage
                </a>
                <ul class="navbar-nav justify-content-end align-items-center w-100 text-white">
                    <li class="nav-item">
                        <button class="add_task btn btn-light border border-primary rounded text-primary">Adicionar Tarefa</button> - 
                    </li>
                    <li class="nav-item p-1">
                        <form class="form-inline d-flex">
                            <input class="form-control mr-sm-2 search" type="search" placeholder="Pesquise..." aria-label="Search">
                            <button class="mx-1 search btn btn-light text-primary border border-prymary rounded" type="submit">Buscar</button>
                        </form>
                    </li>
                </ul>
            </div>
        </nav>
        <!-- Fim do Cabeçalho -->

        <!-- Inicio do Layout -->
        <?= $this->content() ?>
        <!-- Fim do Layout -->

        <!-- Alertas -->
        <div class="toast fixed-bottom m-3" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                <img src="" class="rounded me-2" alt="">
                <strong class="me-auto title_toast">FocusManage</strong>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body">
                Hello, world! This is a toast message.
            </div>
        </div>
        <!-- Fim do Alerta -->

        <!-- Inicio do Rodapé -->
        <footer class="container-fluid bg-black p-3 text-white text-center">
            <h6>Desenvolvido por Ighor Drummond - 2024</h6>
        </footer>
        
        <!-- Bootstrap 5 -->
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

        <!-- Font Awesome -->
        <script src="https://kit.fontawesome.com/c488e9ed48.js" crossorigin="anonymous"></script>

        <!-- Ajax -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.min.js"></script>

        <!-- JQuery -->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.7.1.min.js"></script>

        <!-- Script Padrão -->
        <script defer type="module" src="assets/js/main.js"></script>    
    </body>
</html>